/**
 * Shared NexTake data model.
 *
 * This module is the single source of truth for the article shape used by
 * BOTH the public NexTake blog and this admin console. The public blog reads
 * the same rows (see `supabase/migrations` for the table + RLS definitions),
 * so anything added here must stay in sync with the `articles` table.
 */

export type NavPageId =
  | "home"
  | "articles"
  | "website"
  | "preview"
  | "logout";

/* ------------------------------------------------------------------ */
/* Editorial enums                                                     */
/* ------------------------------------------------------------------ */

export type PublishStatus = "draft" | "published" | "scheduled" | "archived";

export const PUBLISH_STATUSES: PublishStatus[] = [
  "draft",
  "published",
  "scheduled",
  "archived",
];

export type LinkBehavior = "external" | "reader";

export const LINK_BEHAVIORS: Array<{
  value: LinkBehavior;
  label: string;
  hint: string;
}> = [
  {
    value: "external",
    label: "Open directly on the external site",
    hint: "Readers leave NexTake and land on the publisher's page.",
  },
  {
    value: "reader",
    label: "Open in NexTake reader with source link",
    hint: "Readers stay on NexTake; the source is credited in the reader.",
  },
];

export type SyndicationLicense =
  | "fair_use_summary"
  | "full_licensed_syndication"
  | "press_release";

export const SYNDICATION_LICENSES: Array<{
  value: SyndicationLicense;
  label: string;
  hint: string;
}> = [
  {
    value: "fair_use_summary",
    label: "Fair Use Summary",
    hint: "NexTake summary only — no quoted body text.",
  },
  {
    value: "full_licensed_syndication",
    label: "Full Licensed Syndication",
    hint: "Full text permitted under an active licence.",
  },
  {
    value: "press_release",
    label: "Press Release",
    hint: "Distributed verbatim on behalf of the issuer.",
  },
];

/** Categories shared with the main NexTake blog. */
export const CATEGORIES = [
  "AI & Neural Networks",
  "Fintech",
  "Startups",
  "Robotics",
  "Cybersecurity",
  "Cloud & Infrastructure",
  "Hardware & Chips",
  "Policy & Regulation",
  "Science & Space",
  "Other",
] as const;

export type Category = (typeof CATEGORIES)[number];

/** Hero carousel priority — 1 is the lead story. */
export const HERO_PRIORITIES = [1, 2, 3, 4, 5] as const;

/* ------------------------------------------------------------------ */
/* Article                                                             */
/* ------------------------------------------------------------------ */

export interface Article {
  id: string;
  slug: string;

  /* A. Core external link & source */
  sourceUrl: string;
  sourceName: string;
  sourceLogoUrl: string | null;
  originalAuthor: string | null;
  originalPublishedAt: string | null;
  linkBehavior: LinkBehavior;

  /* B. Content & editorial */
  title: string;
  summary: string;
  keyTakeaways: string[];
  category: string;
  tags: string[];
  coverImageUrl: string;
  imageCredit: string | null;
  readTime: string | null;

  /* C. SEO & syndication compliance */
  canonicalUrl: string;
  syndicationLicense: SyndicationLicense | null;
  syndicatedBody: string | null;

  /* D. Feed placement & visibility */
  status: PublishStatus;
  publishedAt: string | null;
  heroPriority: number | null;
  inDailyEdit: boolean;
  isBreaking: boolean;
  relatedCompanyIds: string[];

  /* Telemetry / housekeeping */
  views: number;
  createdAt: string;
  updatedAt: string;
  updatedBy: string | null;
}

/** Payload accepted by create/update. `id` is generated by the database. */
export type ArticleInput = Omit<
  Article,
  "id" | "views" | "createdAt" | "updatedAt" | "updatedBy"
>;

/* ------------------------------------------------------------------ */
/* Supporting records                                                  */
/* ------------------------------------------------------------------ */

export interface Company {
  id: string;
  name: string;
  sector: string | null;
  websiteUrl: string | null;
}

export interface AdminProfile {
  id: string;
  email: string;
  fullName: string | null;
  role: "admin" | "editor";
  avatarUrl: string | null;
}

export interface SiteSettings {
  siteName: string;
  slogan: string;
  heroHeadline: string;
  heroSubhead: string;
  navLinks: Array<{ label: string; href: string }>;
  breakingEnabled: boolean;
  breakingLabel: string;
  dailyEditEnabled: boolean;
  dailyEditSubject: string;
  newsletterEnabled: boolean;
  newsletterHeadline: string;
  contactEmail: string;
  updatedAt: string | null;
}

export interface ActivityItem {
  id: string;
  action: string;
  target: string;
  timestamp: string;
  user: string;
  type: "publish" | "edit" | "subscriber" | "system";
}

export interface SystemMetric {
  label: string;
  value: string;
  change: string;
  positive: boolean;
  technicalDetail: string;
  progressPercent: number;
}
